### PR TITLE
add 500 error email middleware

### PR DESCRIPTION
**Pull request by thevinitgupta**
## Describe your changes

Added a middleware to send email to send email to admin in case of `500 server error`

## Screenshots - If Any (Optional)
image

## Issue ticket number and link - If Any
#215 

## Checklist before requesting a review

- [x] I have performed a self-review of my code.

- [x] Followed the repository's [Contributing Guidelines](https://github.com/dvstechlabs/Noteslify/blob/main/CONTRIBUTING.md).

- [x] I ran the app and tested it locally to verify that it works as expected.

- [x] I have starred the repository.

## Additional Information (Optional)
The following details for the `nodemailer` configuration needs to be updated with admin details : 
error js-2023-02-21-13-02-04
error js-2023-02-21-13-02-34

### CODE REVIEW

**Review by Gauravdarkslayer — CHANGES_REQUESTED** [review]
Please change gmail implementation to outlook implementation and pick the user & pass from env. [Reference](https://github.com/bytemakers/Noteslify/blob/5c523d1a6c16dae01f1de7c55df6f4da0577a8f1/apps/web/backend/routes/auth.js#L311)


Or it can be place in a helper function to avoid code duplication.

**Comment by Gauravdarkslayer** [comment]
@devarshishimpi , should we place mail functionality to a separate file(helper.js) to avoid code duplication ? If yes, should this task be covered in this issue or by creating a separate issue?

**Comment by devarshishimpi** [comment]
> @devarshishimpi , should we place mail functionality to a separate file(helper.js) to avoid code duplication ? If yes, should this task be covered in this issue or by creating a separate issue?

I think the same file works

**Comment by Gauravdarkslayer** [comment]
Alright then! Everything else is looks good for me .

**Review by Gauravdarkslayer — APPROVED** [review]

**Review by devarshishimpi — APPROVED** [review]
Thanks for Contributing!

**Pull request merged**
